name: Test

on: # yamllint disable-line rule:truthy
  - push

jobs:
  unit:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        name: Setup Node.js
        with:
          cache: npm
          node-version: 22.x

      - run: npm ci
        name: Install dependencies

      - run: npm test -- --coverage
        name: Run tests with coverage

      - uses: codecov/codecov-action@v4
        name: Upload results to Codecov
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
